spring:
  profiles:
    include:
      - secret


  kafka:
    bootstrap-servers: localhost:9093

  data:
    mongodb:
      host: localhost
      port: 27018
      database: healthmap
      auto-index-creation: true
