spring:
  profiles:
    include:
      - secret
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:13306/healthmap?useSSL=false&characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    username: root
#    password: application-secret.yml 에 위치

  jpa:
    hibernate:
      ddl-auto: create  # 나중에 제거
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
